import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Header from "@/components/Header";
import PostBreadcrumb from '@/components/PostBreadcrumb';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div id="div-main" className="container">
          <PostBreadcrumb />
          {children}
        </div>
      </body>
    </html >
  );
}
